### ISSUE TITLE
CLI should be BIDS-Apps compliant

### ISSUE THREAD

**Issue by oesteban** [poldracklab/preprocessing-workflow#106]
https://github.com/BIDS-Apps/example#usage

https://github.com/BIDS-Apps/example/blob/master/run.py#L9

https://docs.google.com/document/d/1E1Wi5ONvOVVnGhj21S1bmJJ4kyHFT7tkxnV3C23sjIE/edit#heading=h.2pl9d5noyj6n
- [x] fix up run_workflow.py
- [x] fix up unit tests
- [x]  bids_dir - (positional argument #1) the directory with the input dataset formatted according to the BIDS standard. This directory is read only.
- [x] output_dir - (positional_argument #2) the directory where the output files should be stored. 
 - [x] This is the only directory the pipeline should write to.
- [x] “participant” - (positional_argument #3) indicates that this is a participant level analysis.
- [x] --participant_label - label of the participant that should be analyzed. 
 - [x] The label corresponds to sub-<participant_label> from the BIDS spec (so it does not include “sub-”). 
 - [x] If this parameter is not provided all subjects should be analyzed.
 - [x] Multiple participants can be specified with a space separated list.
